name: PIOMSF2

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Zip the build artifacts
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/
          cp server.js package.json Procfile deploy/
          cd deploy && zip -r ../deploy.zip .
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: PIOMSF2
          environment_name: PIOMSF2-env
          version_label: deploy-${{ github.run_number }}
          region: ap-northeast-2
          deployment_package: deploy.zip
          wait_for_environment_recovery: 180


      - name: Check deployment status
        run: |
          STATUS=$(aws elasticbeanstalk describe-environments --environment-names PIOMSF2-env --query 'Environments[0].Health' --output text)
          if [ "$STATUS" != "Green" ]; then
            echo "Deployment failed. Environment health is $STATUS."
            exit 1
          else
            echo "Deployment succeeded. Environment health is $STATUS."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Retrieve EB Engine Log
        if: failure()
        run: |
          EB_LOG=$(aws elasticbeanstalk describe-environment-resources --environment-name PIOMSF2-env --query 'EnvironmentResources.Instances[0].Id' --output text)
          echo "Instance ID: $EB_LOG"
          COMMAND_ID=$(aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=InstanceIds,Values=$EB_LOG" --parameters 'commands=["sudo cat /var/log/eb-engine.log"]' --query 'Command.CommandId' --output text)
          sleep 10
          aws ssm get-command-invocation --command-id $COMMAND_ID --instance-id $EB_LOG --query 'StandardOutputContent' --output text
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

  check-comments:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Check Pull Request Comments
        id: pr-comments
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENTS=$(gh pr view $PR_NUMBER --json comments --jq '.comments')
          
          UNIQUE_USERS=$(echo "$COMMENTS" | jq -r 'map(.author.login) | unique | length')
          
          if [ $UNIQUE_USERS -lt 2 ]; then
            echo "Not enough unique users ($UNIQUE_USERS) in the pull request comments. At least 2 unique users are required."
            exit 1
          else
            echo "Sufficient unique users ($UNIQUE_USERS) in the pull request comments."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
